const fs = require('fs');
let content = fs.readFileSync('server.ts', 'utf8');

const machineryStr = `    const machinery = [
      {
        id: "m-1",
        ownerId: "owner-1",
        ownerName: "Rajesh Kumar",
        name: "Mahindra Arjun Novo 605",
        brand: "Mahindra",
        model: "Novo 605 DI-i",
        year: 2022,
        type: "Equipment",
        category: "Tractor",
        images: ["https://images.unsplash.com/photo-1594913785162-e6785b493bd2?q=80&w=1000"],
        specifications: [{ key: "Horsepower", value: "57 HP" }, { key: "Cylinders", value: "4" }],
        workingCapacity: "2 Acres/Hour",
        fuelConsumption: "4.5 Liters/Hour",
        fuelType: "Diesel",
        dailyPrice: 2500,
        hourlyPrice: 400,
        weeklyPrice: 15000,
        monthlyPrice: 50000,
        availability: true,
        rating: 4.8,
        reviewsCount: 24,
        distance: "3.5 km",
        location: { lat: 28.6139, lng: 77.2090, address: "Sector 15, Karnal, Haryana" },
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString()
      },
      {
        id: "m-2",
        ownerId: "owner-2",
        ownerName: "Amit Singh",
        name: "John Deere 5310 GearPro",
        brand: "John Deere",
        model: "5310 V5",
        year: 2023,
        type: "Equipment",
        category: "Tractor",
        images: ["https://images.unsplash.com/photo-1595246140625-573b715d11dc?q=80&w=1000"],
        specifications: [{ key: "Horsepower", value: "55 HP" }, { key: "Clutch", value: "Dual" }],
        workingCapacity: "2.2 Acres/Hour",
        fuelConsumption: "4.2 Liters/Hour",
        fuelType: "Diesel",
        dailyPrice: 2800,
        hourlyPrice: 450,
        weeklyPrice: 17000,
        monthlyPrice: 55000,
        availability: true,
        rating: 4.9,
        reviewsCount: 18,
        distance: "5.2 km",
        location: { lat: 28.6239, lng: 77.2190, address: "Nilokheri, Haryana" },
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString()
      },
      {
        id: "m-3",
        ownerId: "owner-4",
        ownerName: "Vikram Patel",
        name: "CLAAS Crop Tiger 30",
        brand: "CLAAS",
        model: "Crop Tiger 30 Terra Trac",
        year: 2021,
        type: "Equipment",
        category: "Harvester",
        images: ["https://images.unsplash.com/photo-1592982537447-6f29402c98d6?w=800"],
        specifications: [{ key: "Cutting Width", value: "7.5 ft" }, { key: "Engine", value: "60 HP" }],
        workingCapacity: "1.5 Acres/Hour",
        fuelConsumption: "6 Liters/Hour",
        fuelType: "Diesel",
        dailyPrice: 8000,
        hourlyPrice: 1200,
        weeklyPrice: 50000,
        monthlyPrice: 180000,
        availability: true,
        rating: 4.7,
        reviewsCount: 35,
        distance: "12 km",
        location: { lat: 28.7041, lng: 77.1025, address: "Sonipat, Haryana" },
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString()
      },
      {
        id: "m-4",
        ownerId: "owner-5",
        ownerName: "Sanjay Sharma",
        name: "Shaktiman Rotavator",
        brand: "Shaktiman",
        model: "Regular Light",
        year: 2022,
        type: "Equipment",
        category: "Rotavator",
        images: ["https://images.unsplash.com/photo-1530541930197-ff16ac917b0e?w=800"],
        specifications: [{ key: "Working Width", value: "5.5 ft" }, { key: "Blades", value: "42" }],
        workingCapacity: "1.8 Acres/Hour",
        fuelConsumption: "N/A (Tractor Driven)",
        fuelType: "None",
        dailyPrice: 1000,
        hourlyPrice: 150,
        weeklyPrice: 6000,
        monthlyPrice: 20000,
        availability: true,
        rating: 4.6,
        reviewsCount: 50,
        distance: "4.5 km",
        location: { lat: 28.5355, lng: 77.3910, address: "Noida, UP" },
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString()
      },
      {
        id: "m-5",
        ownerId: "owner-6",
        ownerName: "Ramesh Yadav",
        name: "Happy Seeder",
        brand: "Dasmesh",
        model: "911",
        year: 2023,
        type: "Equipment",
        category: "Seeder",
        images: ["https://images.unsplash.com/photo-1595246140625-573b715d11dc?w=800"],
        specifications: [{ key: "Rows", value: "9" }, { key: "Row Spacing", value: "9 inches" }],
        workingCapacity: "2.5 Acres/Hour",
        fuelConsumption: "N/A (Tractor Driven)",
        fuelType: "None",
        dailyPrice: 1500,
        hourlyPrice: 250,
        weeklyPrice: 9000,
        monthlyPrice: 30000,
        availability: true,
        rating: 4.8,
        reviewsCount: 22,
        distance: "8 km",
        location: { lat: 28.4595, lng: 77.0266, address: "Gurugram, Haryana" },
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString()
      },
      {
        id: "v-1",
        ownerId: "owner-3",
        ownerName: "Sunil Verma",
        name: "Tata Ace Gold",
        brand: "Tata",
        model: "Gold Diesel Plus",
        year: 2021,
        type: "Vehicle",
        category: "Mini Truck",
        images: ["https://images.unsplash.com/photo-1519003722824-194d4455a60c?q=80&w=1000"],
        specifications: [{ key: "Payload", value: "750 kg" }, { key: "Engine", value: "700cc" }],
        workingCapacity: "N/A",
        fuelConsumption: "18 km/l",
        fuelType: "Diesel",
        capacity: "0.75 Ton",
        dailyPrice: 1200,
        hourlyPrice: 200,
        weeklyPrice: 7500,
        monthlyPrice: 25000,
        availability: true,
        rating: 4.5,
        reviewsCount: 42,
        distance: "2.1 km",
        location: { lat: 28.6339, lng: 77.2290, address: "Taraori, Haryana" },
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString()
      }
    ];`;

const oldStart = 'const machinery = [';
const oldEnd = '];\n    (db as any).machinery = machinery;';

const oldMachineryRegex = /const machinery = \[[\s\S]*?\];\n\s*\(db as any\)\.machinery = machinery;/;

if (oldMachineryRegex.test(content)) {
  content = content.replace(oldMachineryRegex, machineryStr + '\n    (db as any).machinery = machinery;');
  fs.writeFileSync('server.ts', content);
  console.log('Successfully updated machinery seed data.');
} else {
  console.log('Could not find machinery array to replace.');
}

