import React, { useEffect, useState } from 'react';
import { 
  Zap, 
  TrendingUp, 
  TrendingDown, 
  AlertTriangle,
  CheckCircle2,
  ChevronRight,
  ArrowRight,
  Lightbulb,
  Droplets,
  DollarSign,
  Sprout
} from 'lucide-react';
import { motion } from 'motion/react';
import { cn } from '../../lib/utils';
import { AIInsight } from '../../types/analytics';

export default function AIInsights() {
  const [insights, setInsights] = useState<AIInsight[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    // Simulated live generation delay
    setTimeout(() => {
      setInsights([
        { id: "ins1", type: "Profit", title: "Highest Profit Crop", description: "Potatoes are projected to have 25% higher profit margins this season based on current supply-demand trends in your local market.", severity: "success" },
        { id: "ins2", type: "Water", title: "Water Saving Opportunity", description: "Based on soil humidity sensors in Farm North, you can reduce irrigation by 15% without impacting yield. This saves approx. $450/month.", severity: "warning" },
        { id: "ins3", type: "Soil", title: "Soil Nitrogen Critical", description: "Plot B nitrogen levels are below 30%. Delayed fertilization will lead to a 10% yield reduction. Apply Nitrogen supplement within 48 hours.", severity: "error" },
        { id: "ins4", type: "Market", title: "Optimal Harvest Window", description: "Historical price spikes suggest harvesting your Wheat 5 days early to hit the peak market price of $2,300/ton.", severity: "info" },
        { id: "ins5", type: "Pest", title: "High Disease Risk Area", description: "Satellite imagery detected early blight patterns in neighboring farms. Proactive fungicide application recommended for Plot C.", severity: "error" },
      ]);
      setLoading(false);
    }, 800);
  }, []);

  if (loading) {
    return (
      <div className="flex items-center justify-center h-96">
        <div className="animate-spin rounded-full h-12 w-12 border-t-2 border-b-2 border-indigo-600"></div>
      </div>
    );
  }

  const getSeverityStyles = (severity: string) => {
    switch(severity) {
      case 'success': return 'border-green-100 bg-green-50/50 text-green-700 icon-green';
      case 'warning': return 'border-amber-100 bg-amber-50/50 text-amber-700 icon-amber';
      case 'error': return 'border-rose-100 bg-rose-50/50 text-rose-700 icon-rose';
      default: return 'border-indigo-100 bg-indigo-50/50 text-indigo-700 icon-indigo';
    }
  };

  const getIcon = (type: string) => {
    switch(type) {
      case 'Profit': return DollarSign;
      case 'Water': return Droplets;
      case 'Soil': return Sprout;
      case 'Pest': return AlertTriangle;
      default: return Lightbulb;
    }
  };

  return (
    <div className="space-y-12 pb-20">
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-6">
        <div>
          <h1 className="text-4xl font-black text-gray-900 tracking-tight mb-2">AI Strategic Insights</h1>
          <p className="text-gray-500 font-medium">Hyper-intelligent recommendations generated by AgriSmart AI</p>
        </div>
        <button className="px-6 py-3 bg-indigo-600 text-white rounded-2xl text-sm font-bold shadow-lg shadow-indigo-100 hover:bg-indigo-700 transition-all flex items-center gap-2">
          <Zap className="w-4 h-4" />
          Regenerate Insights
        </button>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        {insights.map((insight, idx) => {
          const Icon = getIcon(insight.type);
          const styles = getSeverityStyles(insight.severity);
          
          return (
            <motion.div
              key={insight.id}
              initial={{ opacity: 0, x: idx % 2 === 0 ? -20 : 20 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ delay: idx * 0.1 }}
              className={cn(
                "group p-10 rounded-[40px] border transition-all duration-500 hover:shadow-2xl hover:shadow-gray-100 relative overflow-hidden",
                styles.split(' icon')[0]
              )}
            >
              <div className="flex items-start justify-between mb-8">
                <div className={cn(
                  "p-4 rounded-2xl",
                  insight.severity === 'success' ? 'bg-green-100' :
                  insight.severity === 'warning' ? 'bg-amber-100' :
                  insight.severity === 'error' ? 'bg-rose-100' : 'bg-indigo-100'
                )}>
                  <Icon className={cn("w-6 h-6", styles.split(' icon-')[1] === 'green' ? 'text-green-600' : styles.split(' icon-')[1] === 'amber' ? 'text-amber-600' : styles.split(' icon-')[1] === 'rose' ? 'text-rose-600' : 'text-indigo-600')} />
                </div>
                <div className="flex items-center gap-2 text-[10px] font-black uppercase tracking-[0.2em] opacity-60 group-hover:opacity-100 transition-opacity">
                  <span className="w-1.5 h-1.5 rounded-full bg-current" />
                  {insight.type} Insight
                </div>
              </div>

              <div className="space-y-4">
                <h3 className="text-2xl font-black text-gray-900 tracking-tight leading-none group-hover:text-indigo-600 transition-colors">
                  {insight.title}
                </h3>
                <p className="text-gray-500 font-medium leading-relaxed uppercase tracking-tighter text-sm">
                  {insight.description}
                </p>
              </div>

              <div className="mt-8 pt-8 border-t border-black/5 flex items-center justify-between">
                <button className="flex items-center gap-2 text-[11px] font-black text-indigo-600 uppercase tracking-widest hover:gap-4 transition-all">
                  Take Action <ArrowRight className="w-4 h-4" />
                </button>
                <div className="flex items-center gap-4">
                   <button className="p-3 text-gray-400 hover:text-indigo-600 transition-colors"><CheckCircle2 className="w-5 h-5" /></button>
                   <button className="p-3 text-gray-400 hover:text-rose-600 transition-colors"><AlertTriangle className="w-5 h-5" /></button>
                </div>
              </div>
            </motion.div>
          );
        })}
      </div>

      <div className="bg-gray-900 rounded-[48px] p-12 text-white relative overflow-hidden">
        <div className="absolute top-0 right-0 w-96 h-96 bg-indigo-500/10 rounded-full blur-[100px] -translate-y-1/2 translate-x-1/2" />
        <div className="relative z-10 text-center space-y-8 max-w-2xl mx-auto">
           <div className="inline-flex p-5 bg-white/5 rounded-3xl border border-white/10">
              <Zap className="w-10 h-10 text-yellow-400 fill-yellow-400" />
           </div>
           <h2 className="text-4xl font-black tracking-tight leading-tight uppercase tracking-tighter">Personalized Seasonal Plan</h2>
           <p className="text-lg text-gray-400 font-medium leading-relaxed uppercase tracking-tighter">Our AI has analyzed 12 months of your farm data. We've prepared a custom seasonal blueprint to increase your annual profit by $12k.</p>
           <button className="px-12 py-5 bg-indigo-600 rounded-2xl font-black uppercase tracking-widest text-[11px] hover:bg-indigo-700 shadow-2xl shadow-indigo-900/50 transition-all border border-indigo-500/30">
              View My Custom Plan
           </button>
        </div>
      </div>
    </div>
  );
}
